services:
  aqi-tracker:
    container_name: aqi-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:  
      - AWS_REGION=ap-south-1  # Adjust to your preferred AWS region
      - WAQI_TOKEN=${WAQI_TOKEN}
    restart: always