services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
  #   command: >
  #     sh -c "sleep 10 && ollama pull ${OLLAMA_AQI_MODEL}"

  aqi-tracker:
    container_name: aqi-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:  
      # 1. FORCE THE PROVIDER SO DOCKER NEVER GUESSES
      - LLM_PROVIDER=ollama
      # Overrides the app.py fallback to point to the new container
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_AQI_MODEL=${OLLAMA_AQI_MODEL}
      - WAQI_TOKEN=${WAQI_TOKEN}
    depends_on:
      - ollama
    restart: always

volumes:
  # Persists the downloaded LLM weights across container restarts
  ollama_data: