FROM python:3.13-slim
WORKDIR /app
COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt
COPY aqi_api.py .
COPY .env .
CMD ["uvicorn", "aqi_api:app", "--host", "0.0.0.0", "--port", "8000"]

